name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Compute BASE_PATH
        id: base
        run: |
          REPO="${{ github.repository }}"
          NAME="${REPO#*/}"
          LOWER=$(echo "$NAME" | tr '[:upper:]' '[:lower:]')
          if [[ "$LOWER" == *".github.io" ]]; then
            echo "BASE_PATH=/" >> "$GITHUB_ENV"
          else
            echo "BASE_PATH=/$NAME/" >> "$GITHUB_ENV"
          fi
          echo "Using BASE_PATH=$BASE_PATH"

      - name: Build
        env:
          BASE_PATH: ${{ env.BASE_PATH }}
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
